use crate::error::{Result, SessionError};
use llm::{Content, Message, Role, ToolCall, Usage};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::hash_map::Entry;
use std::collections::{HashMap, HashSet};
use std::fmt;
use std::path::PathBuf;
use std::str::FromStr;
use time::OffsetDateTime;
use time::format_description::well_known::Rfc3339;
use uuid::Uuid;

/// The current on-disk schema version.  The first line of every session and
/// every event envelope carries this value so a future reader can reject a
/// format it cannot safely interpret.
pub const FORMAT_VERSION: u32 = 1;

/// An RFC 3339 timestamp generated by the session crate.
pub type Timestamp = String;

pub(crate) fn now_timestamp() -> Timestamp {
    OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .unwrap_or_else(|_| "1970-01-01T00:00:00Z".to_owned())
}

/// Collision-resistant identity of a conversation session.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionId(Uuid);

impl SessionId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    pub fn parse(value: &str) -> Result<Self> {
        Uuid::parse_str(value.trim())
            .map(Self)
            .map_err(|_| SessionError::InvalidSessionId(value.to_owned()))
    }

    pub fn short(&self) -> String {
        self.to_string().chars().take(8).collect()
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SessionId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl FromStr for SessionId {
    type Err = SessionError;

    fn from_str(value: &str) -> Result<Self> {
        Self::parse(value)
    }
}

/// Identity of one append-only event.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EventId(Uuid);

impl EventId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    pub fn parse(value: &str) -> Result<Self> {
        Uuid::parse_str(value.trim())
            .map(Self)
            .map_err(|_| SessionError::InvalidEvent(format!("invalid event ID `{value}`")))
    }
}

impl Default for EventId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for EventId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Aggregate usage recorded in session metadata.  Usage is intentionally a
/// session-owned DTO instead of a provider-owned type so provider changes do
/// not change the storage schema.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct UsageSummary {
    #[serde(default)]
    pub input_tokens: u64,
    #[serde(default)]
    pub output_tokens: u64,
    #[serde(default)]
    pub cached_tokens: u64,
    #[serde(default)]
    pub reasoning_tokens: u64,
    #[serde(default)]
    pub cost: f64,
    #[serde(default)]
    pub turns: u64,
}

impl UsageSummary {
    pub fn add(&mut self, usage: &Usage) {
        self.input_tokens = self.input_tokens.saturating_add(usage.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(usage.output_tokens);
        self.cached_tokens = self
            .cached_tokens
            .saturating_add(usage.cached_tokens.unwrap_or_default());
        self.reasoning_tokens = self
            .reasoning_tokens
            .saturating_add(usage.reasoning_tokens.unwrap_or_default());
        if let Some(cost) = usage.cost {
            self.cost += cost;
        }
        self.turns = self.turns.saturating_add(1);
    }

    pub fn from_usage(usage: &Usage) -> Self {
        let mut result = Self::default();
        result.add(usage);
        result
    }
}

/// Metadata stored in the session header and evolved by metadata events.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionMetadata {
    #[serde(default = "default_format_version")]
    pub format_version: u32,
    pub id: SessionId,
    #[serde(default)]
    pub title: Option<String>,
    pub workspace_root: PathBuf,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
    #[serde(default)]
    pub provider: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub parent_session: Option<SessionId>,
    #[serde(default)]
    pub compaction_count: u32,
    #[serde(default)]
    pub usage: UsageSummary,
}

fn default_format_version() -> u32 {
    FORMAT_VERSION
}

fn first_message_text(message: &StoredMessage) -> Option<String> {
    message.content.iter().find_map(|content| match content {
        StoredContent::Text { text } if !text.trim().is_empty() => Some(text.clone()),
        _ => None,
    })
}

fn cap_title(value: &str) -> String {
    let first_line = value
        .lines()
        .find(|line| !line.trim().is_empty())
        .unwrap_or(value)
        .trim();
    let max_bytes = 80;
    if first_line.len() <= max_bytes {
        return first_line.to_owned();
    }
    let mut end = max_bytes.saturating_sub(1);
    while end > 0 && !first_line.is_char_boundary(end) {
        end -= 1;
    }
    format!("{}…", &first_line[..end])
}

impl SessionMetadata {
    pub fn new(
        workspace_root: impl Into<PathBuf>,
        provider: Option<String>,
        model: Option<String>,
    ) -> Self {
        let now = now_timestamp();
        Self {
            format_version: FORMAT_VERSION,
            id: SessionId::new(),
            title: None,
            workspace_root: workspace_root.into(),
            created_at: now.clone(),
            updated_at: now,
            provider,
            model,
            parent_session: None,
            compaction_count: 0,
            usage: UsageSummary::default(),
        }
    }

    pub fn with_id(mut self, id: SessionId) -> Self {
        self.id = id;
        self
    }

    pub fn short_id(&self) -> String {
        self.id.short()
    }
}

/// The role representation used by the stable session DTO.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum StoredRole {
    System,
    User,
    Assistant,
    Tool,
}

impl From<&Role> for StoredRole {
    fn from(role: &Role) -> Self {
        match role {
            Role::System => Self::System,
            Role::User => Self::User,
            Role::Assistant => Self::Assistant,
            Role::Tool => Self::Tool,
        }
    }
}

impl From<StoredRole> for Role {
    fn from(role: StoredRole) -> Self {
        match role {
            StoredRole::System => Role::System,
            StoredRole::User => Role::User,
            StoredRole::Assistant => Role::Assistant,
            StoredRole::Tool => Role::Tool,
        }
    }
}

/// Serializable content preserving reasoning, tool-call IDs, and arbitrary
/// JSON tool arguments.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum StoredContent {
    #[serde(rename = "text")]
    Text { text: String },
    #[serde(rename = "reasoning")]
    Reasoning { text: String },
    /// Opaque provider continuation data. It is deliberately data, not prose,
    /// so exporters and compaction summaries never render it.
    #[serde(rename = "opaque")]
    Opaque { provider: String, data: Value },
    #[serde(rename = "tool_call")]
    ToolCall {
        id: String,
        name: String,
        arguments: Value,
    },
    #[serde(rename = "tool_result")]
    ToolResult {
        tool_call_id: String,
        content: String,
        #[serde(default)]
        is_error: bool,
    },
}

/// Serializable form of an `llm::Message`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoredMessage {
    pub role: StoredRole,
    pub content: Vec<StoredContent>,
}

/// Serializable form of an `llm::ToolCall`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoredToolCall {
    pub id: String,
    pub name: String,
    pub arguments: Value,
}

impl From<&ToolCall> for StoredToolCall {
    fn from(call: &ToolCall) -> Self {
        Self {
            id: call.id.clone(),
            name: call.name.clone(),
            arguments: call.arguments.clone(),
        }
    }
}

impl From<StoredToolCall> for ToolCall {
    fn from(call: StoredToolCall) -> Self {
        Self {
            id: call.id,
            name: call.name,
            arguments: call.arguments,
        }
    }
}

impl From<&Content> for StoredContent {
    fn from(content: &Content) -> Self {
        match content {
            Content::Text(text) => Self::Text { text: text.clone() },
            Content::Reasoning(text) => Self::Reasoning { text: text.clone() },
            Content::Opaque { provider, data } => Self::Opaque {
                provider: provider.clone(),
                data: data.clone(),
            },
            Content::ToolCall(call) => Self::ToolCall {
                id: call.id.clone(),
                name: call.name.clone(),
                arguments: call.arguments.clone(),
            },
            Content::ToolResult {
                tool_call_id,
                content,
                is_error,
            } => Self::ToolResult {
                tool_call_id: tool_call_id.clone(),
                content: content.clone(),
                is_error: *is_error,
            },
        }
    }
}

impl From<StoredContent> for Content {
    fn from(content: StoredContent) -> Self {
        match content {
            StoredContent::Text { text } => Content::Text(text),
            StoredContent::Reasoning { text } => Content::Reasoning(text),
            StoredContent::Opaque { provider, data } => Content::Opaque { provider, data },
            StoredContent::ToolCall {
                id,
                name,
                arguments,
            } => Content::ToolCall(ToolCall {
                id,
                name,
                arguments,
            }),
            StoredContent::ToolResult {
                tool_call_id,
                content,
                is_error,
            } => Content::ToolResult {
                tool_call_id,
                content,
                is_error,
            },
        }
    }
}

impl From<&Message> for StoredMessage {
    fn from(message: &Message) -> Self {
        Self {
            role: (&message.role).into(),
            content: message.content.iter().map(StoredContent::from).collect(),
        }
    }
}

impl From<StoredMessage> for Message {
    fn from(message: StoredMessage) -> Self {
        Self {
            role: message.role.into(),
            content: message.content.into_iter().map(Content::from).collect(),
        }
    }
}

impl StoredMessage {
    pub fn to_llm(&self) -> Message {
        self.clone().into()
    }

    pub fn from_llm(message: &Message) -> Self {
        message.into()
    }
}

/// One logical durable event.  The event envelope (ID, sequence, timestamp,
/// and session ID) lives in `SessionEventRecord`; this enum is the stable
/// payload that callers work with.
#[derive(Clone, Debug, PartialEq)]
pub enum SessionEvent {
    UserMessage {
        message: StoredMessage,
    },
    AssistantMessage {
        message: StoredMessage,
    },
    /// A standalone reasoning event is supported for importers.  The agent's
    /// normal path stores reasoning inside its assistant message so it stays
    /// adjacent to the response that produced it.
    Reasoning {
        text: String,
    },
    ToolCall {
        call: StoredToolCall,
    },
    ToolResult {
        tool_call_id: String,
        content: String,
        is_error: bool,
        tool_name: Option<String>,
    },
    CompactionSummary {
        summary: String,
        /// All events at or before this sequence are represented by `summary`
        /// when rebuilding provider context.  The event itself remains in the
        /// append-only log.
        compacted_through: u64,
    },
    ModelChange {
        provider: String,
        model: String,
    },
    Usage {
        usage: UsageSummary,
    },
    MetadataChange {
        title: Option<String>,
    },
    TurnCancelled {
        reason: String,
    },
    Error {
        message: String,
    },
    /// Unknown kinds are retained and exported unchanged.  They do not enter
    /// provider context, which makes loading forward-compatible without
    /// allowing an unrecognised event to corrupt a request.
    Unknown {
        kind: String,
        data: Value,
    },
}

impl SessionEvent {
    /// Convert this event to the provider messages it represents.  Metadata,
    /// usage, diagnostics, and unknown events intentionally produce no
    /// messages; `Session::context_messages` additionally performs grouping
    /// and incomplete-tool repair across event boundaries.
    pub fn to_messages(&self) -> Vec<Message> {
        match self {
            Self::UserMessage { message } | Self::AssistantMessage { message } => {
                vec![message.to_llm()]
            }
            Self::Reasoning { text } => {
                vec![Message::assistant(vec![Content::Reasoning(text.clone())])]
            }
            Self::ToolCall { call } => vec![Message::assistant(vec![Content::ToolCall(
                call.clone().into(),
            )])],
            Self::ToolResult {
                tool_call_id,
                content,
                is_error,
                ..
            } => vec![Message::tool_result(
                tool_call_id.clone(),
                content.clone(),
                *is_error,
            )],
            Self::CompactionSummary { summary, .. } => vec![Message::user(format!(
                "[Generated session summary — not verbatim user text]\n{summary}"
            ))],
            Self::Unknown { .. }
            | Self::ModelChange { .. }
            | Self::Usage { .. }
            | Self::MetadataChange { .. }
            | Self::TurnCancelled { .. }
            | Self::Error { .. } => Vec::new(),
        }
    }

    pub fn kind(&self) -> &str {
        match self {
            Self::UserMessage { .. } => "user_message",
            Self::AssistantMessage { .. } => "assistant_message",
            Self::Reasoning { .. } => "reasoning",
            Self::ToolCall { .. } => "tool_call",
            Self::ToolResult { .. } => "tool_result",
            Self::CompactionSummary { .. } => "compaction",
            Self::ModelChange { .. } => "model_change",
            Self::Usage { .. } => "usage",
            Self::MetadataChange { .. } => "metadata_change",
            Self::TurnCancelled { .. } => "turn_cancelled",
            Self::Error { .. } => "error",
            Self::Unknown { kind, .. } => kind,
        }
    }
}

/// Event plus its append-only envelope.
#[derive(Clone, Debug, PartialEq)]
pub struct SessionEventRecord {
    pub id: EventId,
    pub sequence: u64,
    pub timestamp: Timestamp,
    pub event: SessionEvent,
}

/// A loaded or in-memory session.
#[derive(Clone, Debug, PartialEq)]
pub struct Session {
    pub metadata: SessionMetadata,
    pub events: Vec<SessionEventRecord>,
    /// The immutable metadata snapshot written in the header.  Current
    /// metadata is derived by replaying events; retaining this baseline keeps
    /// export/load from double-counting usage or metadata changes.
    pub(crate) header_metadata: SessionMetadata,
    pub(crate) path: Option<PathBuf>,
    /// Byte offset through the last validated on-disk record. Zero denotes an
    /// in-memory session or a session whose backing file has not been cached.
    pub(crate) validated_bytes: usize,
    /// File identity used to reject a replacement with the same length before
    /// taking the constant-time append path.
    pub(crate) file_identity: Option<(u64, u64)>,
    /// Incremental event-validation state for the cached file prefix.
    pub(crate) event_ids: HashSet<EventId>,
    pub(crate) tracker: ToolCallTracker,
    pub(crate) compaction_boundary: Option<u64>,
}

impl Session {
    pub fn new(metadata: SessionMetadata) -> Self {
        Self {
            header_metadata: metadata.clone(),
            metadata,
            events: Vec::new(),
            path: None,
            validated_bytes: 0,
            file_identity: None,
            event_ids: HashSet::new(),
            tracker: ToolCallTracker::default(),
            compaction_boundary: None,
        }
    }

    pub(crate) fn header_metadata(&self) -> &SessionMetadata {
        &self.header_metadata
    }

    pub fn id(&self) -> SessionId {
        self.metadata.id
    }

    pub fn path(&self) -> Option<&PathBuf> {
        self.path.as_ref()
    }

    pub fn file_path(&self) -> Option<&std::path::Path> {
        self.path.as_deref()
    }

    pub fn title(&self) -> Option<&str> {
        self.metadata.title.as_deref()
    }

    pub fn append(&mut self, event: SessionEvent) -> SessionEventRecord {
        let record = SessionEventRecord {
            id: EventId::new(),
            sequence: self.events.last().map_or(1, |entry| entry.sequence + 1),
            timestamp: now_timestamp(),
            event,
        };
        self.apply_record(record.clone());
        record
    }

    pub(crate) fn append_record(&mut self, record: SessionEventRecord) {
        self.apply_record(record);
    }

    fn apply_record(&mut self, record: SessionEventRecord) {
        self.metadata.updated_at = record.timestamp.clone();
        self.event_ids.insert(record.id);
        if let SessionEvent::CompactionSummary {
            compacted_through, ..
        } = &record.event
        {
            self.compaction_boundary = Some(*compacted_through);
        }
        self.tracker.record(&record.event);
        match &record.event {
            SessionEvent::UserMessage { message } if self.metadata.title.is_none() => {
                if let Some(title) = first_message_text(message) {
                    self.metadata.title = Some(cap_title(&title));
                }
            }
            SessionEvent::ModelChange { provider, model } => {
                self.metadata.provider = Some(provider.clone());
                self.metadata.model = Some(model.clone());
            }
            SessionEvent::MetadataChange { title } => {
                self.metadata.title = title.clone();
            }
            SessionEvent::CompactionSummary { .. } => {
                self.metadata.compaction_count = self.metadata.compaction_count.saturating_add(1);
            }
            SessionEvent::Usage { usage } => {
                self.metadata.usage.input_tokens = self
                    .metadata
                    .usage
                    .input_tokens
                    .saturating_add(usage.input_tokens);
                self.metadata.usage.output_tokens = self
                    .metadata
                    .usage
                    .output_tokens
                    .saturating_add(usage.output_tokens);
                self.metadata.usage.cached_tokens = self
                    .metadata
                    .usage
                    .cached_tokens
                    .saturating_add(usage.cached_tokens);
                self.metadata.usage.reasoning_tokens = self
                    .metadata
                    .usage
                    .reasoning_tokens
                    .saturating_add(usage.reasoning_tokens);
                self.metadata.usage.cost += usage.cost;
                self.metadata.usage.turns = self.metadata.usage.turns.saturating_add(usage.turns);
            }
            _ => {}
        }
        self.events.push(record);
    }

    pub fn context_messages(&self) -> Vec<Message> {
        context_messages(&self.events)
    }
}

/// Tracks tool-call lifetimes across an event log.  Shared by event
/// validation and provider-context reconstruction so both functions agree on
/// which calls are pending, completed, or cancelled — a change to the
/// bookkeeping no longer needs to be replicated in both places.
///
/// Tool-call IDs are globally unique for the life of the log: once an ID has
/// been used (pending or completed), it is never reused.  `TurnCancelled`
/// marks the tail explicitly cancelled and clears the pending queue; `Error`
/// marks it cancelled without clearing so a crash tail stays recoverable.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct ToolCallTracker {
    /// Call IDs awaiting a result, in emission order.
    pending: Vec<String>,
    /// Every call ID ever seen (pending or completed), for reuse detection.
    seen: HashSet<String>,
    /// Call IDs that have received a result.
    completed: HashSet<String>,
    /// True when the tail was explicitly cancelled (`TurnCancelled`/`Error`).
    cancelled: bool,
}

impl ToolCallTracker {
    pub(crate) fn pending(&self) -> &[String] {
        &self.pending
    }

    pub(crate) fn is_pending(&self, id: &str) -> bool {
        self.pending.iter().any(|pending| pending == id)
    }

    pub(crate) fn is_completed(&self, id: &str) -> bool {
        self.completed.contains(id)
    }

    pub(crate) fn is_seen(&self, id: &str) -> bool {
        self.seen.contains(id)
    }

    pub(crate) fn is_cancelled(&self) -> bool {
        self.cancelled
    }

    /// Apply one event's effect on the tool-call lifecycle.  Events that do
    /// not carry tool state are no-ops.  `TurnCancelled` abandons the pending
    /// queue so a late result for a pre-cancellation call is rejected;
    /// crash-tail repair appends durable synthetic `ToolResult` events before
    /// its marker, so repaired pairs are already complete when the marker
    /// lands.  `Error` leaves the queue intact so a crash tail stays
    /// recoverable and `context_messages` can strip the incomplete calls.
    pub(crate) fn record(&mut self, event: &SessionEvent) {
        match event {
            SessionEvent::AssistantMessage { message } => {
                for content in &message.content {
                    if let StoredContent::ToolCall { id, .. } = content {
                        self.push_pending(id);
                    }
                }
                self.cancelled = false;
            }
            SessionEvent::ToolCall { call } => {
                self.push_pending(&call.id);
                self.cancelled = false;
            }
            SessionEvent::ToolResult { tool_call_id, .. } => {
                self.completed.insert(tool_call_id.clone());
                self.seen.insert(tool_call_id.clone());
                if let Some(index) = self.pending.iter().position(|id| id == tool_call_id) {
                    self.pending.remove(index);
                }
            }
            SessionEvent::TurnCancelled { .. } => {
                self.pending.clear();
                self.cancelled = true;
            }
            SessionEvent::Error { .. } => {
                // Errors may follow a stream that ended between a tool call
                // and its result; they make the tail recoverable without
                // clearing the pending queue itself.
                self.cancelled = true;
            }
            _ => {}
        }
    }

    fn push_pending(&mut self, id: &str) {
        self.seen.insert(id.to_owned());
        if !self.is_pending(id) {
            self.pending.push(id.to_owned());
        }
    }
}

/// Convert the durable event path into valid provider messages.  Compaction
/// summaries are explicitly labelled generated context, and incomplete final
/// tool calls are omitted rather than sent as malformed provider history.
pub fn context_messages(events: &[SessionEventRecord]) -> Vec<Message> {
    let selected = events_after_latest_compaction(events);
    let mut messages = Vec::<Message>::new();
    let mut call_locations = HashMap::<String, usize>::new();
    let mut tracker = ToolCallTracker::default();

    for record in selected {
        match &record.event {
            SessionEvent::UserMessage { message } => {
                messages.push(message.to_llm());
            }
            SessionEvent::AssistantMessage { message } => {
                let index = messages.len();
                for content in &message.content {
                    if let StoredContent::ToolCall { id, .. } = content {
                        call_locations.insert(id.clone(), index);
                    }
                }
                messages.push(message.to_llm());
            }
            SessionEvent::Reasoning { text } => {
                if let Some(Message {
                    role: Role::Assistant,
                    content,
                }) = messages.last_mut()
                {
                    content.push(Content::Reasoning(text.clone()));
                } else {
                    messages.push(Message::assistant(vec![Content::Reasoning(text.clone())]));
                }
            }
            SessionEvent::ToolCall { call } => {
                let index = match messages.last() {
                    Some(Message {
                        role: Role::Assistant,
                        ..
                    }) => messages.len() - 1,
                    _ => {
                        messages.push(Message::assistant(Vec::new()));
                        messages.len() - 1
                    }
                };
                let call_id = call.id.clone();
                if let Entry::Vacant(entry) = call_locations.entry(call_id) {
                    messages[index]
                        .content
                        .push(Content::ToolCall(call.clone().into()));
                    entry.insert(index);
                }
            }
            SessionEvent::ToolResult {
                tool_call_id,
                content,
                is_error,
                ..
            } => {
                messages.push(Message::tool_result(
                    tool_call_id.clone(),
                    content.clone(),
                    *is_error,
                ));
            }
            SessionEvent::CompactionSummary { summary, .. } => {
                messages.push(Message::user(format!(
                    "[Generated session summary — not verbatim user text]\n{summary}"
                )));
            }
            SessionEvent::Unknown { .. }
            | SessionEvent::ModelChange { .. }
            | SessionEvent::Usage { .. }
            | SessionEvent::MetadataChange { .. }
            | SessionEvent::TurnCancelled { .. }
            | SessionEvent::Error { .. } => {}
        }
        tracker.record(&record.event);
    }

    // A crash can leave a complete ToolCall line without its result.  Keep the
    // assistant's ordinary text/reasoning, but remove only those calls.  This
    // guarantees the next provider request is structurally valid.
    for (id, index) in call_locations {
        if tracker.is_completed(&id) {
            continue;
        }
        if let Some(Message { content, .. }) = messages.get_mut(index) {
            content.retain(|item| !matches!(item, Content::ToolCall(call) if call.id == id));
        }
    }
    messages.retain(|message| !message.content.is_empty());
    messages
}

/// Find the most recent compaction summary and the sequence boundary it
/// replaces, if any.  Shared by provider-context reconstruction and the
/// compactor so a change to the summary format stays in one place.
///
/// The returned tuple is `(summary_sequence, compacted_through)`: the
/// sequence of the summary event itself and the boundary it declares.  A
/// valid boundary satisfies `compacted_through < summary_sequence` and
/// advances strictly across repeated compactions; see `validate_events`.
pub fn latest_compaction_boundary(events: &[SessionEventRecord]) -> Option<(u64, u64)> {
    events.iter().rev().find_map(|record| {
        if let SessionEvent::CompactionSummary {
            compacted_through, ..
        } = &record.event
        {
            Some((record.sequence, *compacted_through))
        } else {
            None
        }
    })
}

/// Events that remain live after the latest compaction, in provider-context
/// order: the latest summary first, then every non-compaction record with
/// `sequence > compacted_through` in original event order.
///
/// The summary is appended after the events it summarizes, so the live tail
/// spans both sides of it: events with `compacted_through < sequence <
/// summary_sequence` (the preserved recent tail) followed by events with
/// `sequence > summary_sequence` (appended after compaction).  Older
/// compaction summaries are excluded; only the newest summary is retained.
pub fn events_after_latest_compaction(events: &[SessionEventRecord]) -> Vec<&SessionEventRecord> {
    let Some((summary_sequence, compacted_through)) = latest_compaction_boundary(events) else {
        return events.iter().collect();
    };

    let summary = events
        .iter()
        .find(|record| record.sequence == summary_sequence);
    let mut retained = Vec::new();
    if let Some(summary) = summary {
        retained.push(summary);
    }
    retained.extend(events.iter().filter(|record| {
        record.sequence != summary_sequence
            && record.sequence > compacted_through
            && !matches!(record.event, SessionEvent::CompactionSummary { .. })
    }));
    retained
}

/// Validate envelope-level ordering and tool-result references.  An unmatched
/// tool call is allowed only at the end of a log: it is the recoverable state
/// produced by a process crash and is omitted by `context_messages`.
///
/// Validation also enforces compaction-boundary integrity: a summary must not
/// compact through itself or a future event, and repeated compaction
/// boundaries must advance monotonically.
///
/// Tool-call IDs are globally unique across standalone and embedded calls; a
/// reused ID is rejected even after completion or cancellation, because the
/// durable log has no call-instance identity beyond the ID.
pub(crate) fn validate_events(events: &[SessionEventRecord]) -> Result<()> {
    let mut ids = HashSet::new();
    let mut tracker = ToolCallTracker::default();
    let mut compaction_boundary = None;
    for (index, record) in events.iter().enumerate() {
        validate_record(
            record,
            index as u64 + 1,
            &ids,
            &tracker,
            compaction_boundary,
        )?;
        ids.insert(record.id);
        if let SessionEvent::CompactionSummary {
            compacted_through, ..
        } = &record.event
        {
            compaction_boundary = Some(*compacted_through);
        }
        tracker.record(&record.event);
    }
    Ok(())
}

/// Validate one append against the already validated in-memory prefix. This
/// keeps the common append path constant-time with respect to session length;
/// callers fall back to full replay when their cached prefix is stale.
pub(crate) fn validate_next_event(session: &Session, record: &SessionEventRecord) -> Result<()> {
    let expected = session
        .events
        .last()
        .map_or(1, |entry| entry.sequence.saturating_add(1));
    validate_record(
        record,
        expected,
        &session.event_ids,
        &session.tracker,
        session.compaction_boundary,
    )
}

/// Validate an on-disk suffix against cached state without cloning the full
/// event history. The small tool tracker and ID set are copied so a malformed
/// suffix cannot partially mutate the live session.
pub(crate) fn validate_event_suffix(
    session: &Session,
    records: &[SessionEventRecord],
) -> Result<()> {
    let mut ids = session.event_ids.clone();
    let mut tracker = session.tracker.clone();
    let mut boundary = session.compaction_boundary;
    let mut expected = session
        .events
        .last()
        .map_or(1, |record| record.sequence.saturating_add(1));
    for record in records {
        validate_record(record, expected, &ids, &tracker, boundary)?;
        ids.insert(record.id);
        if let SessionEvent::CompactionSummary {
            compacted_through, ..
        } = &record.event
        {
            boundary = Some(*compacted_through);
        }
        tracker.record(&record.event);
        expected = expected.saturating_add(1);
    }
    Ok(())
}

fn validate_record(
    record: &SessionEventRecord,
    expected_sequence: u64,
    ids: &HashSet<EventId>,
    tracker: &ToolCallTracker,
    compaction_boundary: Option<u64>,
) -> Result<()> {
    if record.sequence != expected_sequence {
        return Err(SessionError::InvalidEvent(format!(
            "expected event sequence {expected_sequence}, found {}",
            record.sequence
        )));
    }
    if ids.contains(&record.id) {
        return Err(SessionError::InvalidEvent(format!(
            "duplicate event ID {}",
            record.id
        )));
    }
    if record.timestamp.trim().is_empty() {
        return Err(SessionError::InvalidEvent(format!(
            "event {} has an empty timestamp",
            record.id
        )));
    }

    match &record.event {
        SessionEvent::UserMessage { message } => {
            if !tracker.pending().is_empty() && !tracker.is_cancelled() {
                return Err(SessionError::InvalidEvent(
                    "user message follows an unresolved tool call".into(),
                ));
            }
            if message.role != StoredRole::User {
                return Err(SessionError::InvalidEvent(
                    "user_message does not contain a user message".into(),
                ));
            }
            if message.content.iter().any(|content| {
                matches!(
                    content,
                    StoredContent::ToolCall { .. } | StoredContent::ToolResult { .. }
                )
            }) {
                return Err(SessionError::InvalidEvent(
                    "user_message contains tool content".into(),
                ));
            }
        }
        SessionEvent::AssistantMessage { message } => {
            if message.role != StoredRole::Assistant {
                return Err(SessionError::InvalidEvent(
                    "assistant_message does not contain an assistant message".into(),
                ));
            }
            if message
                .content
                .iter()
                .any(|content| matches!(content, StoredContent::ToolResult { .. }))
            {
                return Err(SessionError::InvalidEvent(
                    "assistant_message contains a tool result".into(),
                ));
            }
            let mut record_ids = HashSet::new();
            for content in &message.content {
                if let StoredContent::ToolCall { id, name, .. } = content {
                    validate_tool_call_id(id, name, tracker, &record_ids)?;
                    record_ids.insert(id.clone());
                }
            }
        }
        SessionEvent::ToolCall { call } => {
            validate_tool_call_id(&call.id, &call.name, tracker, &HashSet::new())?;
        }
        SessionEvent::ToolResult { tool_call_id, .. } => {
            if tool_call_id.trim().is_empty() {
                return Err(SessionError::InvalidEvent(
                    "tool result requires a non-empty tool_call_id".into(),
                ));
            }
            if !tracker.is_pending(tool_call_id) {
                return Err(SessionError::InvalidEvent(format!(
                    "tool result {tool_call_id} has no preceding tool call"
                )));
            }
            let Some(first) = tracker.pending().first() else {
                return Err(SessionError::InvalidEvent(format!(
                    "tool result {tool_call_id} has no preceding tool call"
                )));
            };
            if first != tool_call_id {
                return Err(SessionError::InvalidEvent(format!(
                    "tool result {tool_call_id} is out of order; expected {first}"
                )));
            }
        }
        SessionEvent::CompactionSummary {
            compacted_through, ..
        } => {
            if *compacted_through >= record.sequence {
                return Err(SessionError::InvalidEvent(format!(
                    "compaction boundary {compacted_through} must precede its summary event {}",
                    record.sequence
                )));
            }
            if let Some(previous) = compaction_boundary
                && *compacted_through <= previous
            {
                return Err(SessionError::InvalidEvent(format!(
                    "compaction boundary {compacted_through} does not advance past {previous}"
                )));
            }
        }
        SessionEvent::TurnCancelled { .. }
        | SessionEvent::Error { .. }
        | SessionEvent::ModelChange { .. }
        | SessionEvent::Usage { .. }
        | SessionEvent::MetadataChange { .. }
        | SessionEvent::Reasoning { .. }
        | SessionEvent::Unknown { .. } => {}
    }
    Ok(())
}

fn validate_tool_call_id(
    id: &str,
    name: &str,
    tracker: &ToolCallTracker,
    record_ids: &HashSet<String>,
) -> Result<()> {
    if id.trim().is_empty() || name.trim().is_empty() {
        return Err(SessionError::InvalidEvent(
            "tool call requires a non-empty ID and name".into(),
        ));
    }
    if record_ids.contains(id) || tracker.is_pending(id) {
        return Err(SessionError::InvalidEvent(format!(
            "duplicate pending tool call {id}"
        )));
    }
    if tracker.is_seen(id) {
        return Err(SessionError::InvalidEvent(format!(
            "reused tool call ID {id}"
        )));
    }
    Ok(())
}

/// Convert a provider usage value into the storage DTO.
pub fn usage_summary(usage: &Usage) -> UsageSummary {
    UsageSummary::from_usage(usage)
}

/// A structural view of a session's conversation, rebuilt from the durable
/// event log for transcript rendering.  The session crate owns the event
/// model, so it also owns the tool-result pairing that keeps a snapshot
/// consistent with [`context_messages`].  Presentation formatting (tool
/// summaries, bounded argument strings) is layered on top by the agent.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SessionSnapshotEntry {
    User {
        text: String,
    },
    Assistant {
        markdown: String,
        reasoning: String,
    },
    Tool {
        name: String,
        /// Raw structured arguments.  Callers format these for display.
        arguments: Value,
        ok: bool,
        output: String,
        error: Option<String>,
    },
}

/// Rebuild a transcript-style view of the conversation.  A `ToolResult`
/// event is matched back to the `ToolCall` that produced it (the same
/// pairing performed by [`context_messages`]), so the snapshot stays in sync
/// with the provider history as new event kinds are added.  A result
/// without a preceding call — possible after repair — becomes a standalone
/// tool entry so nothing is dropped from the view.
pub fn snapshot_entries(session: &Session) -> Vec<SessionSnapshotEntry> {
    let mut entries = Vec::new();
    let mut tool_indices = HashMap::<String, usize>::new();

    for record in &session.events {
        match &record.event {
            SessionEvent::UserMessage { message } => {
                let text = message.content.iter().find_map(|content| match content {
                    StoredContent::Text { text } => Some(text.clone()),
                    _ => None,
                });
                if let Some(text) = text.filter(|text| !text.is_empty()) {
                    entries.push(SessionSnapshotEntry::User { text });
                }
            }
            SessionEvent::AssistantMessage { message } => {
                let mut markdown = String::new();
                let mut reasoning = String::new();
                for content in &message.content {
                    match content {
                        StoredContent::Text { text } => {
                            if !markdown.is_empty() {
                                markdown.push('\n');
                            }
                            markdown.push_str(text);
                        }
                        StoredContent::Reasoning { text } => {
                            if !reasoning.is_empty() {
                                reasoning.push('\n');
                            }
                            reasoning.push_str(text);
                        }
                        StoredContent::ToolCall { .. }
                        | StoredContent::ToolResult { .. }
                        | StoredContent::Opaque { .. } => {}
                    }
                }
                if !markdown.is_empty() || !reasoning.is_empty() {
                    entries.push(SessionSnapshotEntry::Assistant {
                        markdown,
                        reasoning,
                    });
                }
            }
            SessionEvent::ToolCall { call } => {
                let index = entries.len();
                tool_indices.insert(call.id.clone(), index);
                entries.push(SessionSnapshotEntry::Tool {
                    name: call.name.clone(),
                    arguments: call.arguments.clone(),
                    ok: false,
                    output: String::new(),
                    error: None,
                });
            }
            SessionEvent::ToolResult {
                tool_call_id,
                content,
                is_error,
                tool_name,
            } => {
                if let Some(index) = tool_indices.get(tool_call_id).copied()
                    && let Some(SessionSnapshotEntry::Tool {
                        name,
                        ok,
                        output,
                        error,
                        ..
                    }) = entries.get_mut(index)
                {
                    if let Some(tool_name) = tool_name {
                        *name = tool_name.clone();
                    }
                    *ok = !is_error;
                    *output = content.clone();
                    *error = is_error.then(|| content.clone());
                } else {
                    entries.push(SessionSnapshotEntry::Tool {
                        name: tool_name.clone().unwrap_or_else(|| "tool".into()),
                        arguments: Value::Object(Default::default()),
                        ok: !is_error,
                        output: content.clone(),
                        error: is_error.then(|| content.clone()),
                    });
                }
            }
            SessionEvent::Reasoning { text } => {
                if let Some(SessionSnapshotEntry::Assistant { reasoning, .. }) = entries.last_mut()
                {
                    if !reasoning.is_empty() {
                        reasoning.push('\n');
                    }
                    reasoning.push_str(text);
                } else {
                    entries.push(SessionSnapshotEntry::Assistant {
                        markdown: String::new(),
                        reasoning: text.clone(),
                    });
                }
            }
            SessionEvent::CompactionSummary { summary, .. } => {
                entries.push(SessionSnapshotEntry::Assistant {
                    markdown: format!("_Session summary:_\n\n{summary}"),
                    reasoning: String::new(),
                });
            }
            SessionEvent::ModelChange { .. }
            | SessionEvent::Usage { .. }
            | SessionEvent::MetadataChange { .. }
            | SessionEvent::TurnCancelled { .. }
            | SessionEvent::Error { .. }
            | SessionEvent::Unknown { .. } => {}
        }
    }

    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn message_round_trip_preserves_reasoning_and_tool_ids() {
        let message = Message {
            role: Role::Assistant,
            content: vec![
                Content::Reasoning("thinking".into()),
                Content::Text("answer".into()),
                Content::ToolCall(ToolCall {
                    id: "call-1".into(),
                    name: "read".into(),
                    arguments: json!({"path": "é.txt"}),
                }),
            ],
        };
        assert_eq!(StoredMessage::from_llm(&message).to_llm(), message);
    }

    #[test]
    fn incomplete_final_tool_call_is_not_sent_to_provider() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        session.append(SessionEvent::UserMessage {
            message: StoredMessage::from_llm(&Message::user("hi")),
        });
        session.append(SessionEvent::AssistantMessage {
            message: StoredMessage::from_llm(&Message::assistant(vec![Content::Text(
                "working".into(),
            )])),
        });
        session.append(SessionEvent::ToolCall {
            call: StoredToolCall {
                id: "call".into(),
                name: "read".into(),
                arguments: json!({}),
            },
        });
        let messages = session.context_messages();
        assert_eq!(messages.len(), 2);
        assert_eq!(
            messages[1],
            Message::assistant(vec![Content::Text("working".into())])
        );
    }

    #[test]
    fn first_user_message_provides_a_stable_display_title() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        session.append(SessionEvent::UserMessage {
            message: StoredMessage::from_llm(&Message::user("Fix the login flow")),
        });
        assert_eq!(session.title(), Some("Fix the login flow"));
    }

    #[test]
    fn usage_is_aggregated_in_metadata() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        session.append(SessionEvent::Usage {
            usage: UsageSummary {
                input_tokens: 2,
                turns: 1,
                ..UsageSummary::default()
            },
        });
        assert_eq!(session.metadata.usage.input_tokens, 2);
        assert_eq!(session.metadata.usage.turns, 1);
    }

    #[test]
    fn snapshot_entries_matches_tool_results_to_their_calls() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        session.append(SessionEvent::UserMessage {
            message: StoredMessage::from_llm(&Message::user("hi")),
        });
        session.append(SessionEvent::AssistantMessage {
            message: StoredMessage::from_llm(&Message::assistant(vec![Content::Text(
                "working".into(),
            )])),
        });
        session.append(SessionEvent::ToolCall {
            call: StoredToolCall {
                id: "call-1".into(),
                name: "read".into(),
                arguments: json!({ "path": "Cargo.toml" }),
            },
        });
        session.append(SessionEvent::ToolResult {
            tool_call_id: "call-1".into(),
            content: "file contents".into(),
            is_error: false,
            tool_name: Some("read".into()),
        });

        let snapshot = snapshot_entries(&session);
        assert_eq!(snapshot.len(), 3);
        assert_eq!(
            snapshot[0],
            SessionSnapshotEntry::User { text: "hi".into() }
        );
        assert_eq!(
            snapshot[1],
            SessionSnapshotEntry::Assistant {
                markdown: "working".into(),
                reasoning: String::new(),
            }
        );
        // The result is paired back to the call that produced it, keeping
        // the arguments from the call while taking the status from the result.
        assert_eq!(
            snapshot[2],
            SessionSnapshotEntry::Tool {
                name: "read".into(),
                arguments: json!({ "path": "Cargo.toml" }),
                ok: true,
                output: "file contents".into(),
                error: None,
            }
        );
    }

    #[test]
    fn snapshot_entries_keeps_orphan_tool_results() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        session.append(SessionEvent::ToolResult {
            tool_call_id: "call-9".into(),
            content: "lonely output".into(),
            is_error: true,
            tool_name: Some("bash".into()),
        });
        let snapshot = snapshot_entries(&session);
        assert_eq!(
            snapshot,
            vec![SessionSnapshotEntry::Tool {
                name: "bash".into(),
                arguments: Value::Object(Default::default()),
                ok: false,
                output: "lonely output".into(),
                error: Some("lonely output".into()),
            }]
        );
    }

    // --- SESSION-1: compaction tail preservation --------------------------

    fn push_user(session: &mut Session, text: &str) {
        session.append(SessionEvent::UserMessage {
            message: StoredMessage::from_llm(&Message::user(text)),
        });
    }

    fn push_assistant(session: &mut Session, text: &str) {
        session.append(SessionEvent::AssistantMessage {
            message: StoredMessage::from_llm(&Message::assistant(vec![Content::Text(text.into())])),
        });
    }

    fn push_tool_call(session: &mut Session, id: &str, name: &str) {
        session.append(SessionEvent::ToolCall {
            call: StoredToolCall {
                id: id.into(),
                name: name.into(),
                arguments: json!({}),
            },
        });
    }

    fn push_tool_result(session: &mut Session, id: &str) {
        session.append(SessionEvent::ToolResult {
            tool_call_id: id.into(),
            content: "output".into(),
            is_error: false,
            tool_name: Some("read".into()),
        });
    }

    fn push_summary(session: &mut Session, summary: &str, compacted_through: u64) {
        session.append(SessionEvent::CompactionSummary {
            summary: summary.into(),
            compacted_through,
        });
    }

    fn retained_sequences(session: &Session) -> Vec<u64> {
        events_after_latest_compaction(&session.events)
            .iter()
            .map(|record| record.sequence)
            .collect()
    }

    fn message_text(message: &Message) -> String {
        message
            .content
            .iter()
            .filter_map(|content| match content {
                Content::Text(text) => Some(text.clone()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    #[test]
    fn compaction_keeps_summary_first_then_the_live_tail() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "user1");
        push_assistant(&mut session, "assistant1");
        push_user(&mut session, "user2");
        push_assistant(&mut session, "assistant2");
        push_summary(&mut session, "summary-one", 2);

        validate_events(&session.events).unwrap();
        // The summary (sequence 5) leads; the preserved recent tail (3, 4)
        // follows in original event order.
        assert_eq!(retained_sequences(&session), vec![5, 3, 4]);

        let messages = session.context_messages();
        assert_eq!(messages.len(), 3);
        assert!(matches!(messages[0].role, Role::User));
        assert!(message_text(&messages[0]).contains("summary-one"));
        assert!(matches!(messages[1].role, Role::User));
        assert_eq!(message_text(&messages[1]), "user2");
        assert!(matches!(messages[2].role, Role::Assistant));
        assert_eq!(message_text(&messages[2]), "assistant2");
    }

    #[test]
    fn events_appended_after_compaction_follow_the_retained_tail() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "user1");
        push_assistant(&mut session, "assistant1");
        push_user(&mut session, "user2");
        push_assistant(&mut session, "assistant2");
        push_summary(&mut session, "summary-one", 2);
        push_user(&mut session, "user3");

        validate_events(&session.events).unwrap();
        assert_eq!(retained_sequences(&session), vec![5, 3, 4, 6]);

        let messages = session.context_messages();
        assert_eq!(messages.len(), 4);
        assert_eq!(message_text(&messages[3]), "user3");
    }

    #[test]
    fn repeated_compaction_retains_only_the_newest_summary() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "user1");
        push_assistant(&mut session, "assistant1");
        push_user(&mut session, "user2");
        push_assistant(&mut session, "assistant2");
        push_summary(&mut session, "summary-one", 2);
        push_user(&mut session, "user3");
        push_assistant(&mut session, "assistant3");
        push_summary(&mut session, "summary-two", 6);

        validate_events(&session.events).unwrap();
        // Only the newest summary survives, followed by its live tail.
        assert_eq!(retained_sequences(&session), vec![8, 7]);

        let messages = session.context_messages();
        assert_eq!(messages.len(), 2);
        assert!(message_text(&messages[0]).contains("summary-two"));
        assert!(
            !message_text(&messages[0]).contains("summary-one"),
            "the older summary must not leak into the retained tail"
        );
        assert_eq!(message_text(&messages[1]), "assistant3");
    }

    #[test]
    fn invalid_compaction_boundaries_fail_validation() {
        // A summary must not compact through itself.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "user1");
        push_assistant(&mut session, "assistant1");
        push_summary(&mut session, "bad", 3);
        assert!(validate_events(&session.events).is_err());

        // Nor through a future event.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "user1");
        push_assistant(&mut session, "assistant1");
        push_summary(&mut session, "bad", 99);
        assert!(validate_events(&session.events).is_err());

        // Repeated compaction boundaries must advance monotonically.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "user1");
        push_assistant(&mut session, "assistant1");
        push_user(&mut session, "user2");
        push_assistant(&mut session, "assistant2");
        push_summary(&mut session, "first", 2);
        push_user(&mut session, "user3");
        push_assistant(&mut session, "assistant3");
        push_summary(&mut session, "second", 2);
        assert!(validate_events(&session.events).is_err());
    }

    #[test]
    fn compaction_boundary_keeps_tool_call_result_pairs() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "read this");
        push_tool_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        push_assistant(&mut session, "done");
        push_summary(&mut session, "summary-one", 1);

        validate_events(&session.events).unwrap();
        assert_eq!(retained_sequences(&session), vec![5, 2, 3, 4]);

        // The retained result still has its call: every tool result in the
        // reconstructed provider history is paired with a tool call.
        let messages = session.context_messages();
        let mut calls = HashSet::new();
        let mut results = Vec::new();
        for message in &messages {
            for content in &message.content {
                match content {
                    Content::ToolCall(call) => {
                        calls.insert(call.id.clone());
                    }
                    Content::ToolResult { tool_call_id, .. } => results.push(tool_call_id.clone()),
                    _ => {}
                }
            }
        }
        assert_eq!(results, vec!["call-1".to_owned()]);
        assert!(calls.contains("call-1"));
    }

    // --- SESSION-5: tool-call replay validation ---------------------------

    fn push_assistant_call(session: &mut Session, id: &str, name: &str) {
        session.append(SessionEvent::AssistantMessage {
            message: StoredMessage {
                role: StoredRole::Assistant,
                content: vec![StoredContent::ToolCall {
                    id: id.into(),
                    name: name.into(),
                    arguments: json!({}),
                }],
            },
        });
    }

    #[test]
    fn completed_tool_call_ids_cannot_be_reused() {
        // Reuse with a second result is still reuse.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_tool_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        session.append(SessionEvent::TurnCancelled {
            reason: "done".into(),
        });
        push_tool_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        assert!(validate_events(&session.events).is_err());

        // Reuse without any second result is also rejected.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_tool_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        session.append(SessionEvent::TurnCancelled {
            reason: "done".into(),
        });
        push_tool_call(&mut session, "call-1", "read");
        assert!(validate_events(&session.events).is_err());
    }

    #[test]
    fn empty_tool_call_ids_and_names_are_rejected() {
        for (id, name) in [("", "read"), ("call-1", ""), ("  ", "read")] {
            let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
            push_user(&mut session, "hi");
            push_tool_call(&mut session, id, name);
            assert!(
                validate_events(&session.events).is_err(),
                "standalone call id={id:?} name={name:?} must be rejected"
            );

            let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
            push_user(&mut session, "hi");
            push_assistant_call(&mut session, id, name);
            assert!(
                validate_events(&session.events).is_err(),
                "embedded call id={id:?} name={name:?} must be rejected"
            );
        }

        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_assistant_call(&mut session, "call-1", "read");
        session.append(SessionEvent::ToolResult {
            tool_call_id: String::new(),
            content: "output".into(),
            is_error: false,
            tool_name: Some("read".into()),
        });
        assert!(validate_events(&session.events).is_err());
    }

    #[test]
    fn cancelled_tool_call_ids_cannot_be_reused() {
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_tool_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        session.append(SessionEvent::TurnCancelled {
            reason: "user stopped".into(),
        });
        push_tool_call(&mut session, "call-1", "read");
        assert!(validate_events(&session.events).is_err());
    }

    #[test]
    fn standalone_and_embedded_calls_share_one_id_namespace() {
        // Standalone first, embedded reuse second.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_tool_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        session.append(SessionEvent::TurnCancelled {
            reason: "done".into(),
        });
        push_assistant_call(&mut session, "call-1", "read");
        assert!(validate_events(&session.events).is_err());

        // Embedded first, standalone reuse second.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_assistant_call(&mut session, "call-1", "read");
        push_tool_result(&mut session, "call-1");
        session.append(SessionEvent::TurnCancelled {
            reason: "done".into(),
        });
        push_tool_call(&mut session, "call-1", "read");
        assert!(validate_events(&session.events).is_err());
    }

    #[test]
    fn context_reconstruction_never_yields_orphan_results_or_dangling_calls() {
        // A valid mixed standalone/embedded batch reconstructs paired.
        let mut session = Session::new(SessionMetadata::new("/workspace", None, None));
        push_user(&mut session, "hi");
        push_assistant_call(&mut session, "embedded-1", "read");
        push_tool_call(&mut session, "standalone-1", "bash");
        push_tool_result(&mut session, "embedded-1");
        push_tool_result(&mut session, "standalone-1");
        validate_events(&session.events).unwrap();

        let messages = session.context_messages();
        let mut calls = HashSet::new();
        let mut results = Vec::new();
        for message in &messages {
            for content in &message.content {
                match content {
                    Content::ToolCall(call) => {
                        calls.insert(call.id.clone());
                    }
                    Content::ToolResult { tool_call_id, .. } => results.push(tool_call_id.clone()),
                    _ => {}
                }
            }
        }
        assert_eq!(calls.len(), 2);
        assert_eq!(results.len(), 2);
        for result in &results {
            assert!(
                calls.contains(result),
                "tool result {result} has no paired call in provider context"
            );
        }

        // An incomplete crash tail is stripped, never dangled.
        push_tool_call(&mut session, "dangling-1", "read");
        let messages = session.context_messages();
        let dangling = messages
            .iter()
            .flat_map(|message| message.content.iter())
            .any(|content| matches!(content, Content::ToolCall(call) if call.id == "dangling-1"));
        assert!(!dangling);
    }
}
